# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / NeoForge Properties
# https://maven.neoforged.net/releases/net/neoforged/neoforge/
minecraft_version=26.2
minecraft_version_range=[26.2,)
neo_version=26.2.0.32-beta
neo_version_range=[26.2,)

# Mod Properties
mod_id=simplehudenhanced
mod_name=Simple Hud Enhanced
mod_license=MIT
mod_version=4.7.5.1
maven_group=com.soradgaming
archives_base_name=simple-hud-enhanced+26.2

# Dependencies
# https://modrinth.com/mod/cloth-config/versions?g=26.2&l=neoforge
cloth_config_version=26.2.155
