# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft / NeoForge Properties
# https://maven.neoforged.net/releases/net/neoforged/neoforge/
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
neo_version=21.11.44
neo_version_range=[21.11,21.12)

# Mod Properties
mod_id=simplehudenhanced
mod_name=Simple Hud Enhanced
mod_license=MIT
mod_version=4.7.5.1
maven_group=com.soradgaming
archives_base_name=simple-hud-enhanced+1.21.11

# Dependencies
# https://modrinth.com/mod/cloth-config/versions?g=1.21.11&l=neoforge
cloth_config_version=21.11.152
