# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
minecraft_support_version_key = \u003e\u003d26.2- \u003c26.3-
#https://maven.fabricmc.net/net/fabricmc/fabric-loader/
loader_version=0.19.1
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=4.7.5
maven_group=com.soradgaming
archives_base_name=simple-hud-enhanced+26.2

# Dependencies
#https://modrinth.com/mod/fabric-api/versions?g=26.2
fabric_version=0.152.1+26.2
#https://modrinth.com/mod/cloth-config/changelog?g=26.2
cloth_config_version=26.2.155
#https://modrinth.com/mod/modmenu/versions?g=26.2
modmenu_version=20.0.0-beta.2
#https://modrinth.com/mod/trinkets/versions?g=26.2
trinkets_version=3.10.0
#https://modrinth.com/mod/cardinal-components-api/versions?g=26.2
cardinal_components_api_version=8.0.0
